SELECT IMEK AS "Ime kompanije", PIB AS "Poreski identifikacioni broj",
COUNT(ZJMBG) AS "Broj zaposlenih"
FROM KOMPANIJA
LEFT JOIN RADNO_MESTO ON KOMPANIJA.IDK = RADNO_MESTO.IDK
WHERE GODINA_OSN < 2000
AND (DATUMDO IS NULL OR DATUMDO > CURRENT_DATE)
GROUP BY KOMPANIJA.IDK, IMEK, PIB
ORDER BY COUNT(ZJMBG) DESC;
