WITH BrojRadnihMesta AS (
    SELECT ZJMBG, COUNT(*) AS BrojMesta
    FROM RADNO_MESTO
    WHERE POZICIJA != 'Rukovodilac sektora'
    GROUP BY ZJMBG
    HAVING COUNT(*) >= 2
)
SELECT IME AS "Ime", PREZIME AS "Prezime"
FROM ZAPOSLENI
JOIN BrojRadnihMesta ON ZAPOSLENI.JMBG = BrojRadnihMesta.ZJMBG
WHERE ZAPOSLENI.JMBG NOT IN (
    SELECT DISTINCT ZJMBG
    FROM RADNO_MESTO
    WHERE POZICIJA = 'Rukovodilac sektora'
)
ORDER BY PREZIME, IME;
