SELECT IMEK AS "Ime kompanije", COUNT(ZJMBG) AS "Broj zaposlenih"
FROM KOMPANIJA
JOIN RADNO_MESTO ON KOMPANIJA.IDK = RADNO_MESTO.IDK
WHERE DATUMDO IS NULL
GROUP BY KOMPANIJA.IDK, IMEK
ORDER BY COUNT(ZJMBG) DESC
LIMIT 1;
