CREATE VIEW STATISTIKA_ZAPOSLENI AS
SELECT ZAPOSLENI.IME, ZAPOSLENI.PREZIME,
    COUNT(DISTINCT RADNO_MESTO.POZICIJA) AS "Broj različitih pozicija",
    AVG(DATEDIFF(DAY, RADNO_MESTO.DATUMOD, RADNO_MESTO.DATUMDO)) AS "Prosečno vreme provedeno na radnim mestima"
FROM ZAPOSLENI
JOIN RADNO_MESTO ON ZAPOSLENI.JMBG = RADNO_MESTO.ZJMBG
WHERE RADNO_MESTO.DATUMDO IS NOT NULL
GROUP BY ZAPOSLENI.JMBG, ZAPOSLENI.IME, ZAPOSLENI.PREZIME;
