DELETE FROM RADNO_MESTO
WHERE ZJMBG IN (
    SELECT ZJMBG
    FROM RADNO_MESTO
    JOIN KOMPANIJA ON RADNO_MESTO.IDK = KOMPANIJA.IDK
    WHERE KOMPANIJA.GODINA_OSN < 2000
    AND DATEDIFF(DAY, DATUMOD, DATUMDO) > 1000
);
